---
- name: copy Docker Compose files
  copy:
    src: files/{{ item }}
    dest: /somewhere/yourproject/{{ item }}
  loop:
  - docker-compose.yml
  # - docker-compose.prod.yml

# use files parameter to use multiple docker-compose.yml files
# mind the _v2 suffix
- name: deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: /somewhere/yourproject
    files:
    - docker-compose.yml
    # - docker-compose.prod.yml