---
- name: Recursively remove directory
  ansible.builtin.file:
    path: /opt/app
    state: absent

- name: copy files for proxy
  ansible.builtin.copy:
    src: files/
    dest: /opt/app/
    mode: preserve

# use files parameter to use multiple docker-compose.yml files
# mind the _v2 suffix
- name: deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/app
    files:
    - docker-compose.yml