services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"

    extra_hosts:
      - "test.me-ua.com:192.168.10.217"
    volumes:
      - ./testmil.conf:/etc/nginx/conf.d/testmil.conf

