- hosts: tfAns
  tasks:

    - name: Install gnupg
      apt: pkg=gnupg state=latest update_cache=true

    - name: Add ansible repository
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible

    - name: add key for terraform
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg

    - name: Add terraform repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com mantic main"
        state: present

    - name: Update&Upgrade
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ansible
          - terraform

    # - name: Install ansible
    #   apt: pkg=ansible state=latest update_cache=true

    # - name: Install terraform
    #   apt: pkg=terraform state=latest update_cache=true
    