# https://phoenixnap.com/kb/letsencrypt-docker

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: proxyNginx
    ports:
      - "80:80"
      - "443:443"

    extra_hosts:
      - "test.me-ua.com:192.168.10.217"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /mnt/vmdata/certbot/www/:/var/www/certbot/:ro
      - /mnt/vmdata/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /mnt/vmdata/certbot/www/:/var/www/certbot/:rw
      - /mnt/vmdata/certbot/conf/:/etc/letsencrypt/:rw
